from __future__ import annotations

import json
from pathlib import Path

from incidentlens.langgraph_adapter import resume_graph
from incidentlens.report import render_text
from incidentlens.workflow import IncidentLensApp


def main() -> int:
    output = Path("examples/output")
    output.mkdir(parents=True, exist_ok=True)
    runtime = Path(".incidentlens/proof")
    runtime.mkdir(parents=True, exist_ok=True)
    app = IncidentLensApp(runtime / "incidents.db")
    paused = app.investigate("payment-unreachable", engine="langgraph", inject_failure=True)
    paused_text = render_text(paused)

    second_process = IncidentLensApp(runtime / "incidents.db")
    resumed = resume_graph(second_process, paused.incident_id, True, "Evidence reviewed in a separate process")
    resumed_text = render_text(resumed)

    markdown = f"""# LangGraph deterministic replay proof

Generated by `scripts/generate_proof.py` using two separate `IncidentLensApp` instances and a durable SQLite LangGraph checkpointer.

## Invocation 1 - interrupted at human approval

```text
{paused_text}
```

## Invocation 2 - resumed from the same incident ID

```text
{resumed_text}
```

## Safety statement

No production action occurred. Approval created a verification plan only; the final state is `approved_pending_verification`.
"""
    (output / "langgraph-replay-run.md").write_text(markdown, encoding="utf-8")
    (output / "langgraph-replay-state.json").write_text(
        json.dumps(resumed.to_dict(), indent=2, sort_keys=True), encoding="utf-8"
    )
    print(output / "langgraph-replay-run.md")
    print(output / "langgraph-replay-state.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

